HappyItemPanel = {};

--ctor
function HappyItemPanel:New(o, pGameObject)
    o = o or
        {
            gameObject = nil,
            transform = nil,
        };

    --define more members of 'o'


	setmetatable(o, self);
    self.__index = self;
    if (pGameObject) then
        o:InitPanel(pGameObject);
    end

	return o;
end


--initialize the panel with the passed gameObject
function HappyItemPanel:InitPanel(pGameObject)

    self.gameObject = pGameObject;
    self.transform = pGameObject.transform;

    self:_FindComponent(pGameObject);

    --if other initialization instructions are necessary, write them here


end

function HappyItemPanel:ReleasePanel()
    self.gameObject = nil;
    self.transform = nil;

    self:_ReleaseComponent();

    --if you want to handle other thing when releasing the panel, write them here


end

--this function is auto generated by script, and should NOT be modified manually.
function HappyItemPanel:_FindComponent(pGameObject)
--make_lua_panel_tag1_do_not_delete
    local tTransform = pGameObject.transform;
    self.textObject = SceneObjectPathTool.FindEx(tTransform, "").gameObject;
    self.textObject1 = SceneObjectPathTool.FindEx(tTransform, "Text").gameObject;
    self.textObject2 = SceneObjectPathTool.FindEx(tTransform, "Text").gameObject;
    self.textObject3 = SceneObjectPathTool.FindEx(tTransform, "Text").gameObject;
--make_lua_panel_tag2_do_not_delete
end

--this function is auto generated by script, and should NOT be modified manually.
function HappyItemPanel:_ReleaseComponent()
--make_lua_panel_tag3_do_not_delete
    self.textObject = nil;
    self.textObject1 = nil;
    self.textObject2 = nil;
    self.textObject3 = nil;
--make_lua_panel_tag4_do_not_delete
end
