MyContent1Panel = {};

--ctor
function MyContent1Panel:New(o, pGameObject)
    o = o or
        {
            gameObject = nil,
            transform = nil,
        };

    --define more members of 'o'


	setmetatable(o, self);
    self.__index = self;
    if (pGameObject) then
        o:InitPanel(pGameObject);
    end

	return o;
end


--initialize the panel with the passed gameObject
function MyContent1Panel:InitPanel(pGameObject)

    self.gameObject = pGameObject;
    self.transform = pGameObject.transform;

    self:_FindComponent(pGameObject);

    --if other initialization instructions are necessary, write them here


end

function MyContent1Panel:ReleasePanel()
    self.gameObject = nil;
    self.transform = nil;

    self:_ReleaseComponent();

    --if you want to handle other thing when releasing the panel, write them here


end

--this function is auto generated by script, and should NOT be modified manually.
function MyContent1Panel:_FindComponent(pGameObject)
--make_lua_panel_tag1_do_not_delete
    local tTransform = pGameObject.transform;
    self.text1 = SceneObjectPathTool.FindEx(tTransform, "Canvas/Text (1)").gameObject:GetComponent("Text");
    self.text2 = SceneObjectPathTool.FindEx(tTransform, "Canvas/Text (2)").gameObject:GetComponent("Text");
    self.rectTransformList = {
        SceneObjectPathTool.FindEx(tTransform, "Canvas/Image").gameObject:GetComponent("RectTransform"),
        SceneObjectPathTool.FindEx(tTransform, "Canvas/Image (1)").gameObject:GetComponent("RectTransform"),
        SceneObjectPathTool.FindEx(tTransform, "Canvas/Image (3)").gameObject:GetComponent("RectTransform"),
        SceneObjectPathTool.FindEx(tTransform, "Canvas/Image (4)").gameObject:GetComponent("RectTransform"),
        SceneObjectPathTool.FindEx(tTransform, "Canvas/Image (5)").gameObject:GetComponent("RectTransform"),
        SceneObjectPathTool.FindEx(tTransform, "Canvas/Image (6)").gameObject:GetComponent("RectTransform"),
    };
    --i am daddy not mami
    self.daddyArray = {
        SceneObjectPathTool.FindEx(tTransform, "../Daddy1"),
        SceneObjectPathTool.FindEx(tTransform, "../Daddy2"),
        SceneObjectPathTool.FindEx(tTransform, "../Daddy3"),
        SceneObjectPathTool.FindEx(tTransform, "../DaddyWithSameName[0]"),
        SceneObjectPathTool.FindEx(tTransform, "../DaddyWithSameName[1]"),
        SceneObjectPathTool.FindEx(tTransform, "../DaddyWithSameName[2]"),
    };
--make_lua_panel_tag2_do_not_delete
end

--this function is auto generated by script, and should NOT be modified manually.
function MyContent1Panel:_ReleaseComponent()
--make_lua_panel_tag3_do_not_delete
    self.text1 = nil;
    self.text2 = nil;
    self.rectTransformList = nil;
    self.daddyArray = nil;
--make_lua_panel_tag4_do_not_delete
end
