MyContent1Panel = {};

function MyContent1Panel.Test(go)
    local panel = MyContent1Panel:New(nil, go);
    panel:SomeAction();
end

--ctor
function MyContent1Panel:New(o, pGameObject)
	local o = o or {gameObject = nil, transform = nil};
	setmetatable(o, self);
    self.__index = self;
    if (pGameObject) then
        o:InitPanel(pGameObject);
    end
	return o;
end


--initialize the panel with the passed gameObject
function MyContent1Panel:InitPanel(pGameObject)
    
    self.gameObject = pGameObject;
    self.transform = pGameObject.transform;

    self:_FindComponent(pGameObject);


    --if other initialization instructions are necessary, write them here

end

--this function is auto generated by script, and should NOT be modified manually.
function MyContent1Panel:_FindComponent(pGameObject)
--make_lua_panel_tag1_do_not_delete
    local tTransform = pGameObject.transform;
    self.text1 = SceneObjectPathTool.FindEx(tTransform, "Canvas/Text (1)").gameObject:GetComponent("Text");
    self.text2 = SceneObjectPathTool.FindEx(tTransform, "Canvas/Text (2)").gameObject:GetComponent("Text");
    self.rectTransformList = {
        SceneObjectPathTool.FindEx(tTransform, "Canvas/Image").gameObject:GetComponent("RectTransform"),
        SceneObjectPathTool.FindEx(tTransform, "Canvas/Image (1)").gameObject:GetComponent("RectTransform"),
        SceneObjectPathTool.FindEx(tTransform, "Canvas/Image (3)").gameObject:GetComponent("RectTransform"),
        SceneObjectPathTool.FindEx(tTransform, "Canvas/Image (4)").gameObject:GetComponent("RectTransform"),
        SceneObjectPathTool.FindEx(tTransform, "Canvas/Image (5)").gameObject:GetComponent("RectTransform"),
        SceneObjectPathTool.FindEx(tTransform, "Canvas/Image (6)").gameObject:GetComponent("RectTransform"),
    };
    self.daddyArray = {
        SceneObjectPathTool.FindEx(tTransform, "../Daddy1"),
        SceneObjectPathTool.FindEx(tTransform, "../Daddy2"),
        SceneObjectPathTool.FindEx(tTransform, "../Daddy3"),
        SceneObjectPathTool.FindEx(tTransform, "../DaddyWithSameName[0]"),
        SceneObjectPathTool.FindEx(tTransform, "../DaddyWithSameName[1]"),
        SceneObjectPathTool.FindEx(tTransform, "../DaddyWithSameName[2]"),
    };
--make_lua_panel_tag2_do_not_delete
end

function MyContent1Panel:SomeAction()
    print("happy new year 2018");

    --idk why that methods and properties from base type cannot be used at this cstolua version, so don't care too much about the code below
    --不知道为啥这个版本的wrap没把基类的属性和方法注册进去，所以下面的代码看看就好，很多基类属性没法用
    self.text1.text = "ahahaha";
    self.text2.text = "happy new year 2018";

    self.rectTransformList[1].sizeDelta = Vector2.New(200, 10);
    
    for i = 1, #self.daddyArray do
        self.daddyArray[i].localPosition = Vector3.New(0,0,0);
    end
end