MakeLuaPanelTemplate = {};

--ctor
function MakeLuaPanelTemplate:New(o, pGameObject)
	local o = o or {gameObject = nil, transform = nil};
	setmetatable(o, self);
    self.__index = self;
    if (pGameObject) then
        o:InitPanel(pGameObject);
    end
	return o;
end


--initialize the panel with the passed gameObject
function MakeLuaPanelTemplate:InitPanel(pGameObject)
    
    self.gameObject = pGameObject;
    self.transform = pGameObject.transform;

    self:_FindComponent(pGameObject);


    --if other initialization instructions are necessary, write them here

end

--this function is auto generated by script, and should NOT be modified manually.
function MakeLuaPanelTemplate:_FindComponent(pGameObject)
--make_lua_panel_tag1_do_not_delete

    --the following fields(public or serializable) were NOT processed,
    --you can process them OUT of this function if necessary

--make_lua_panel_tag2_do_not_delete
end